### ISSUE TITLE
Participant manager module not found

### ISSUE THREAD

**Issue by positlabs** [facebookincubator/spark-ar-core-libs#5]
I'm confused why I'm getting this error when the lib is very obviously imported in spark. Maybe it's related to using the lib inside of a block? I also have the package imported in the block.

"JavaScript error: Cannot find module 'spark-ar-participant-manager'"

<img width="859" alt="Screen Shot 2022-06-01 at 10 28 51 AM" src="https://user-images.githubusercontent.com/1918844/171455477-6734eea4-3f8e-4db4-b23d-b77e2daf51db.png">

**Comment by positlabs** [comment]
I can reproduce the issue when I try adding the block to a new project. Even if I uninstall the package and re-import it, the same error happens. 

<img width="687" alt="Screen Shot 2022-06-23 at 11 31 34 AM" src="https://user-images.githubusercontent.com/1918844/175339091-ce4e6efc-5794-4433-9da0-dc32ef6baa85.png">
<img width="259" alt="Screen Shot 2022-06-23 at 11 31 28 AM" src="https://user-images.githubusercontent.com/1918844/175339093-62ab786c-f6ba-4d2f-99cf-44d152e85e37.png">
<img width="732" alt="Screen Shot 2022-06-23 at 11 31 16 AM" src="https://user-images.githubusercontent.com/1918844/175339095-8da3c8b5-789c-4868-bf1b-9a2a0fcc2ffc.png">

Here are some files to test. 
https://drive.google.com/drive/folders/1Xtcghyj_LNz5p9X_zj8pQ7S3ifNuI1iQ?usp=sharing

Try adding that block to a new project and see what happens. 

Something else to note - maybe it's a bug in spark, but I can't move that block outside of the block folder, or it fails to import. I'm guessing it loses track of the associated script.

**Comment by larrylin28** [comment]
I think this is an issue with Spark not specific to this library. Please report the bug via the "Report" button on the side bar

**Comment by positlabs** [comment]
I'll do that, thanks!
